name: Github Actions
on: [push, pull_request]
permissions:
  contents: write
  
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: media_kit_test
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build apk --split-per-abi --verbose
      - run: |
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/media_kit_test_android-arm64-v8a.apk
      - uses: actions/upload-artifact@v1
        with:
          name: media_kit_test_android-arm64-v8a
          path: media_kit_test/build/app/outputs/flutter-apk/media_kit_test_android-arm64-v8a.apk
